# Generated by Django 3.1.3 on 2023-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20230311_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgoods',
            name='id',
        ),
        migrations.AlterField(
            model_name='allgoods',
            name='Product_Number',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
