# Generated by Django 3.1.3 on 2023-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_allgoods_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgoods',
            name='Product_img',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
