# Generated by Django 3.1.3 on 2023-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodID', models.CharField(blank=True, max_length=100, null=True)),
                ('goodType', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
