# Generated by Django 3.1.3 on 2023-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotgoods',
            name='goodName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotgoods',
            name='goodPrice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotgoods',
            name='goodUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
