# Generated by Django 3.1.3 on 2023-04-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230412_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotgoods',
            name='goodID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='hotgoods',
            name='goodName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='hotgoods',
            name='goodPrice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品价格展示'),
        ),
        migrations.AlterField(
            model_name='hotgoods',
            name='goodType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主页展示类型'),
        ),
        migrations.AlterField(
            model_name='hotgoods',
            name='goodUrl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品图片网址'),
        ),
    ]
