# Generated by Django 3.1.3 on 2023-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bannershow'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=48, null=True, verbose_name='提交邮箱')),
            ],
        ),
    ]
