# Generated by Django 3.1.3 on 2023-06-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_emailsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PONumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poNumber', models.CharField(blank=True, max_length=16, null=True, verbose_name='PO-Number')),
                ('mockUp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mock-Up')),
                ('orderDate', models.CharField(blank=True, max_length=64, null=True, verbose_name='Order-Date')),
                ('paymentReceived', models.CharField(blank=True, max_length=64, null=True, verbose_name='Payment-Received')),
                ('balance', models.CharField(blank=True, max_length=64, null=True, verbose_name='Balance')),
                ('orderStatus', models.CharField(blank=True, max_length=32, null=True, verbose_name='Order-Status')),
                ('testReport', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test-Report')),
                ('eta', models.CharField(blank=True, max_length=64, null=True, verbose_name='ETA')),
            ],
        ),
    ]
