from django.db import models
import datetime

# Create your models here.
class ALLHotGoods(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(max_length=100, blank=True, null=True)
    img = models.ImageField(upload_to='img/', blank=True)

class selectDingdans(models.Model):
    time = models.CharField(max_length=20, blank=True, null=True)
    username = models.CharField(max_length=20, blank=True, null=True)
    dingdanname = models.CharField(max_length=20, blank=True, null=True)
    upmoney = models.CharField(max_length=20, blank=True, null=True)
    pi = models.CharField(max_length=20, blank=True, null=True)
    com = models.CharField(max_length=100, blank=True, null=True)
    dingdanID = models.CharField(max_length=20, blank=True, null=True)
    type = models.CharField(max_length=20, blank=True, null=True)
    num = models.CharField(max_length=20, blank=True, null=True)
    money = models.CharField(max_length=20, blank=True, null=True)
    othermoney = models.CharField(max_length=20, blank=True, null=True)
    allmoney = models.CharField(max_length=20, blank=True, null=True)

class Dingdans(models.Model):
    index = models.CharField(max_length=20, blank=True, null=True)
    pi = models.CharField(max_length=20, blank=True, null=True)
    kehu = models.CharField(max_length=20, blank=True, null=True)
    goods = models.CharField(max_length=20, blank=True, null=True)
    user = models.CharField(max_length=20, blank=True, null=True)
    money = models.CharField(max_length=20, blank=True, null=True)
    poID = models.CharField(max_length=20, blank=True, null=True)
    poTime = models.CharField(max_length=20, blank=True, null=True)
    label = models.CharField(max_length=20, blank=True, null=True)
    
class CaiGou(models.Model):
    time = models.CharField(max_length=20, blank=True, null=True)
    user = models.CharField(max_length=20, blank=True, null=True)
    goods = models.CharField(max_length=20, blank=True, null=True)
    upMoney = models.CharField(max_length=20, blank=True, null=True)
    PI = models.CharField(max_length=20, blank=True, null=True)
    com = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    type = models.CharField(max_length=20, blank=True, null=True)
    num = models.CharField(max_length=20, blank=True, null=True)
    money = models.CharField(max_length=20, blank=True, null=True)
    otherMoney = models.CharField(max_length=20, blank=True, null=True)
    allMoney = models.CharField(max_length=20, blank=True, null=True)

class AllGoods(models.Model):
    Product_Name = models.CharField(max_length=80, blank=True, null=True)
    Product_Number = models.CharField(max_length=10, primary_key=True)
    Product_img = models.CharField(max_length=80, blank=True, null=True)
    Product_IsHazmat = models.CharField(max_length=20, blank=True, null=True)
    Description = models.CharField(max_length=1000, blank=True, null=True)
    Summary = models.CharField(max_length=80, blank=True, null=True)
    Product_Type = models.CharField(max_length=80, blank=True, null=True)
    Category = models.CharField(max_length=300, blank=True, null=True)
    Keywords = models.CharField(max_length=300, blank=True, null=True)
    Product_Color = models.CharField(max_length=500, blank=True, null=True)
    Material = models.CharField(max_length=100, blank=True, null=True)
    Size_Group = models.CharField(max_length=80, blank=True, null=True)
    Size_Values = models.CharField(max_length=80, blank=True, null=True)
    Shape = models.CharField(max_length=80, blank=True, null=True)
    Theme = models.CharField(max_length=80, blank=True, null=True)

    Origin = models.CharField(max_length=80, blank=True, null=True)
    Imprint_Method = models.CharField(max_length=80, blank=True, null=True)
    Imprint_Color = models.CharField(max_length=80, blank=True, null=True)
    Imprint_Size = models.CharField(max_length=80, blank=True, null=True)
    Imprint_Location = models.CharField(max_length=80, blank=True, null=True)
    Price_Includes = models.CharField(max_length=80, blank=True, null=True)
    Sequence = models.CharField(max_length=4, blank=True, null=True)
    Currency = models.CharField(max_length=3, blank=True, null=True)
    Always_Free_Setup = models.CharField(max_length=3, blank=True, null=True)
    Upcharge_Name = models.CharField(max_length=30, blank=True, null=True)
    Upcharge_Criteria_1 = models.CharField(max_length=30, blank=True, null=True)
    Upcharge_Criteria_2 = models.CharField(max_length=30, blank=True, null=True)
    Upcharge_Type = models.CharField(max_length=20, blank=True, null=True)
    Upcharge_Level = models.CharField(max_length=20, blank=True, null=True)
    Service_Charge = models.CharField(max_length=20, blank=True, null=True)
    UQ1 = models.CharField(max_length=6, blank=True, null=True)
    UQ2 = models.CharField(max_length=6, blank=True, null=True)
    UQ3 = models.CharField(max_length=6, blank=True, null=True)
    UQ4 = models.CharField(max_length=6, blank=True, null=True)
    UQ5 = models.CharField(max_length=6, blank=True, null=True)
    UQ6 = models.CharField(max_length=6, blank=True, null=True)
    UQ7 = models.CharField(max_length=6, blank=True, null=True)
    UQ8 = models.CharField(max_length=6, blank=True, null=True)
    UQ9 = models.CharField(max_length=6, blank=True, null=True)
    UQ10 = models.CharField(max_length=6, blank=True, null=True)
    UP1 = models.CharField(max_length=6, blank=True, null=True)
    UP2 = models.CharField(max_length=6, blank=True, null=True)
    UP3 = models.CharField(max_length=6, blank=True, null=True)
    UP4 = models.CharField(max_length=6, blank=True, null=True)
    UP5 = models.CharField(max_length=6, blank=True, null=True)
    UP6 = models.CharField(max_length=6, blank=True, null=True)
    UP7 = models.CharField(max_length=6, blank=True, null=True)
    UP8 = models.CharField(max_length=6, blank=True, null=True)
    UP9 = models.CharField(max_length=6, blank=True, null=True)
    UP10 = models.CharField(max_length=6, blank=True, null=True)
    UD1 = models.CharField(max_length=6, blank=True, null=True)
    UD2 = models.CharField(max_length=6, blank=True, null=True)
    UD3 = models.CharField(max_length=6, blank=True, null=True)
    UD4 = models.CharField(max_length=6, blank=True, null=True)
    UD5 = models.CharField(max_length=6, blank=True, null=True)
    UD6 = models.CharField(max_length=6, blank=True, null=True)
    UD7 = models.CharField(max_length=6, blank=True, null=True)
    UD8 = models.CharField(max_length=6, blank=True, null=True)
    UD9 = models.CharField(max_length=6, blank=True, null=True)
    UD10 = models.CharField(max_length=6, blank=True, null=True)
    Upcharge_Details = models.CharField(max_length=80, blank=True, null=True)
    

    Production_Time = models.CharField(max_length=20, blank=True, null=True)
    Rush_Service = models.CharField(max_length=10, blank=True, null=True)
    Rush_Time = models.CharField(max_length=20, blank=True, null=True)
    Same_Day_Service = models.CharField(max_length=20, blank=True, null=True)
    Packaging = models.CharField(max_length=40, blank=True, null=True)
    Shipping_Items = models.CharField(max_length=40, blank=True, null=True)
    Shipping_Dimensions = models.CharField(max_length=40, blank=True, null=True)
    Shipping_Weight = models.CharField(max_length=40, blank=True, null=True)
    Shipper_Bills_By = models.CharField(max_length=20, blank=True, null=True)
    Shipping_Info = models.CharField(max_length=40, blank=True, null=True)
    Free_Shipping = models.CharField(max_length=4, blank=True, null=True)


    Q1 = models.CharField(max_length=8, blank=True, null=True)
    Q2 = models.CharField(max_length=8, blank=True, null=True)
    Q3 = models.CharField(max_length=8, blank=True, null=True)
    Q4 = models.CharField(max_length=8, blank=True, null=True)
    Q5 = models.CharField(max_length=8, blank=True, null=True)
    Q6 = models.CharField(max_length=8, blank=True, null=True)
    Q7 = models.CharField(max_length=8, blank=True, null=True)
    Q8 = models.CharField(max_length=8, blank=True, null=True)
    Q9 = models.CharField(max_length=8, blank=True, null=True)
    Q10 = models.CharField(max_length=8, blank=True, null=True)
    P1 = models.CharField(max_length=8, blank=True, null=True)
    P2 = models.CharField(max_length=8, blank=True, null=True)
    P3 = models.CharField(max_length=8, blank=True, null=True)
    P4 = models.CharField(max_length=8, blank=True, null=True)
    P5 = models.CharField(max_length=8, blank=True, null=True)
    P6 = models.CharField(max_length=8, blank=True, null=True)
    P7 = models.CharField(max_length=8, blank=True, null=True)
    P8 = models.CharField(max_length=8, blank=True, null=True)
    P9 = models.CharField(max_length=8, blank=True, null=True)
    P10 = models.CharField(max_length=8, blank=True, null=True)
    D1 = models.CharField(max_length=8, blank=True, null=True)
    D2 = models.CharField(max_length=8, blank=True, null=True)
    D3 = models.CharField(max_length=8, blank=True, null=True)
    D4 = models.CharField(max_length=8, blank=True, null=True)
    D5 = models.CharField(max_length=8, blank=True, null=True)
    D6 = models.CharField(max_length=8, blank=True, null=True)
    D7 = models.CharField(max_length=8, blank=True, null=True)
    D8 = models.CharField(max_length=8, blank=True, null=True)
    D9 = models.CharField(max_length=8, blank=True, null=True)
    D10 = models.CharField(max_length=8, blank=True, null=True)

    Distributor_View_Only = models.CharField(max_length=4, blank=True, null=True)
    Carrier_Information = models.CharField(max_length=100, blank=True, null=True)
    Market_Segment = models.CharField(max_length=40, blank=True, null=True)
    create_time = models.DateField('提交日期',default=datetime.date.today)