# Generated by Django 3.1.3 on 2023-03-28 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='问题')),
                ('answer', models.CharField(blank=True, max_length=512, null=True, verbose_name='回答')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=40, null=True)),
                ('lname', models.CharField(blank=True, max_length=40, null=True)),
                ('company', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('contact', models.CharField(blank=True, max_length=400, null=True)),
                ('create_time', models.DateField(default=datetime.date.today, verbose_name='提交日期')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=40, null=True, verbose_name='first name')),
                ('lname', models.CharField(blank=True, max_length=40, null=True, verbose_name='last name')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='email')),
                ('company', models.CharField(blank=True, max_length=64, null=True, verbose_name='company')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('product_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='商品名称')),
                ('product_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='商品代码')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='计划日期')),
                ('quantity', models.CharField(blank=True, max_length=40, null=True, verbose_name='需求数量')),
                ('contact', models.CharField(blank=True, max_length=400, null=True, verbose_name='留言内容')),
                ('create_time', models.DateField(default=datetime.date.today, verbose_name='提交日期')),
            ],
        ),
    ]
