# Generated by Django 3.1.3 on 2023-04-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='date',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='计划日期'),
        ),
    ]
