# Generated by Django 3.1.3 on 2023-03-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customblacklist_custominfo_customlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodid', models.CharField(blank=True, max_length=40, null=True)),
                ('tranid', models.CharField(blank=True, max_length=40, null=True)),
                ('check1', models.CharField(blank=True, max_length=40, null=True)),
                ('check2', models.CharField(blank=True, max_length=40, null=True)),
                ('check3', models.CharField(blank=True, max_length=40, null=True)),
                ('check4', models.CharField(blank=True, max_length=40, null=True)),
                ('check5', models.CharField(blank=True, max_length=40, null=True)),
                ('tran1', models.CharField(blank=True, max_length=40, null=True)),
                ('tran2', models.CharField(blank=True, max_length=40, null=True)),
                ('tran3', models.CharField(blank=True, max_length=40, null=True)),
                ('tran4', models.CharField(blank=True, max_length=40, null=True)),
                ('tran5', models.CharField(blank=True, max_length=40, null=True)),
                ('eva1', models.CharField(blank=True, max_length=40, null=True)),
                ('eva2', models.CharField(blank=True, max_length=40, null=True)),
                ('eva3', models.CharField(blank=True, max_length=40, null=True)),
                ('eva4', models.CharField(blank=True, max_length=40, null=True)),
                ('eva5', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
