# Generated by Django 3.1.3 on 2023-03-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_logistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='id',
        ),
        migrations.AlterField(
            model_name='logistics',
            name='goodid',
            field=models.CharField(default=1, max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
